[workspace.package]
edition = "2024"
publish = false
version = "0.0.1-pre"

[workspace.lints.rust]
missing_docs = "warn"
unsafe_code  = "forbid"

[workspace]
members  = ["crates/miden-multisig-client", "crates/test-utils"]
resolver = "3"

[workspace.dependencies]
miden-multisig-test-utils = { path = "crates/test-utils" }

miden-client              = { default-features = false, version = "0.13" }
miden-client-sqlite-store = "0.13"
rand                      = "0.9"
thiserror                 = { default-features = false, version = "2" }
tokio                     = { default-features = false, version = "1.40" }
